#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Colors
RED='\033[0;31m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Patterns
requiredPattern="^(Add|Implement|Create|Fix|Resolve|Correct|Improve|Enhance|Optimize|Refactor|Reorganize|Clean|Document|Update|Remove|Merge|Integrate|Style|Format|Test) .*$"

# Check commit message
message="$(cat $1)"

if ! [[ $message =~ $requiredPattern ]]; then
    echo "-"
    echo -e "${RED}🚨 Wrong commit message! 😕${NC}"
    echo "The commit message must have this format:"
    echo -e "${YELLOW}<verb in imperative mood> <what was done>${NC}"
    echo "Allowed verbs in imperative mood:"
    echo -e "${YELLOW}Add${NC}: Adding new features or functionality."
    echo -e "${YELLOW}Implement${NC}: Implementing a specific feature or functionality."
    echo -e "${YELLOW}Create${NC}: Creating new components, modules, or files."
    echo -e "${YELLOW}Fix${NC}: Fixing a bug or issue."
    echo -e "${YELLOW}Resolve${NC}: Resolving an issue or a bug."
    echo -e "${YELLOW}Correct${NC}: Correcting a bug or issue."
    echo -e "${YELLOW}Improve${NC}: Improving existing functionality or performance."
    echo -e "${YELLOW}Enhance${NC}: Enhancing existing features or performance."
    echo -e "${YELLOW}Optimize${NC}: Optimizing code or performance."
    echo -e "${YELLOW}Refactor${NC}: Refactoring code for better structure or readability without changing its functionality."
    echo -e "${YELLOW}Reorganize${NC}: Reorganizing code or files for better structure."
    echo -e "${YELLOW}Clean${NC}: Cleaning up code or removing unnecessary code."
    echo -e "${YELLOW}Document${NC}: Adding or updating documentation."
    echo -e "${YELLOW}Update${NC}: Updating existing documentation."
    echo -e "${YELLOW}Remove${NC}: Removing unused dependencies or packages."
    echo -e "${YELLOW}Merge${NC}: Merging branches."
    echo -e "${YELLOW}Integrate${NC}: Integrating changes from another branch."
    echo -e "${YELLOW}Style${NC}: Styling code or UI changes without affecting functionality."
    echo -e "${YELLOW}Format${NC}: Formatting code according to guidelines."
    echo -e "${YELLOW}Test${NC}: Adding or updating tests."
    echo "Example: Add user authentication"
    echo "-"
    echo "Your commit message was:"
    echo -e "${CYAN}$message${NC}"
    echo "-"
    echo "For more information, check the script in .husky/commit-msg"
    echo "-"
    exit 1
fi