#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Colors
RED='\033[0;31m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Patterns
branchNamePattern="^rels\/rel[0-9]+\/.+$"

# Check branch naming (Could be moved to pre-push file)
current_branch=$(git rev-parse --abbrev-ref HEAD)

if ! [[ $current_branch =~ $branchNamePattern ]];
then
    echo "-"
    echo -e "${RED}🚨 Wrong branch name! 😕${NC}"
    echo "Your branch name should match the template:"
    echo -e "${YELLOW}rels/rel<release number>/<task name and number>${NC}"
    echo "Example: rels/rel1/NIM-960-fix-something"
    echo "-"
    echo "Your current branch name is:"
    echo -e ${CYAN}$current_branch${NC}
    echo "-"
    echo "For more information, check script in .husky/commit-msg"
    echo "-"
    exit 1
fi

